


FINTRAFFIC_VESSELS_API: 'https://meri.digitraffic.fi/api/ais/v1/locations'


focus_area:
  latitude: [59, 60.7]
  longitude: [21, 30.5]

MMSI_COUNTRY_MAP:
  201: Albania
  202: Andorra
  203: Austria
  204: Azores
  205: Belgium
  206: Belarus
  207: Bulgaria
  208: Vatican City
  209: Cyprus
  210: Cyprus
  211: Germany
  212: Cyprus
  213: Georgia
  214: Moldova
  215: Malta
  216: Armenia
  218: Germany
  219: Denmark
  220: Denmark
  224: Spain
  225: Spain
  226: France
  227: France
  228: France
  230: Finland
  231: Faroe Islands
  232: United Kingdom
  233: United Kingdom
  234: United Kingdom
  235: United Kingdom
  236: Gibraltar
  237: Greece
  238: Croatia
  239: Greece
  240: Greece
  241: Greece
  242: Morocco
  243: Hungary
  244: Netherlands
  245: Netherlands
  246: Netherlands
  247: Italy
  248: Malta
  249: Malta
  250: Ireland
  251: Iceland
  252: Liechtenstein
  253: Luxembourg
  254: Monaco
  255: Madeira
  256: Malta
  257: Norway
  258: Norway
  259: Norway
  261: Poland
  262: Montenegro
  263: Portugal
  264: Romania
  265: Sweden
  266: Sweden
  267: Slovak Republic
  268: San Marino
  269: Switzerland
  270: Czech Republic
  271: Turkey
  272: Ukraine
  273: Russia 
  274: Russia #Macedonia
  275: Latvia
  276: Estonia
  277: Lithuania
  278: Slovenia
  279: Serbia
  301: Anguilla
  303: Alaska
  304: Antigua and Barbuda
  305: Antigua and Barbuda
  306: Netherlands Antilles
  307: Aruba
  308: Bahamas
  309: Bahamas
  310: Bermuda
  311: Bahamas
  312: Belize
  314: Barbados
  316: Canada
  319: Cayman Islands
  321: Costa Rica
  323: Cuba
  325: Dominica
  327: Dominican Republic
  329: Guadeloupe
  330: Grenada
  331: Greenland
  332: Guatemala
  334: Honduras
  336: Haiti
  338: United States
  339: Jamaica
  341: Saint Kitts and Nevis
  343: Saint Lucia
  345: Mexico
  347: Martinique
  348: Montserrat
  350: Nicaragua
  351: Panama
  352: Panama
  353: Panama
  354: Panama
  355: null
  356: null
  357: null
  358: Puerto Rico
  359: El Salvador
  361: Saint Pierre and Miquelon
  362: Trinidad and Tobago
  364: Turks and Caicos Islands
  366: United States
  367: United States
  368: United States
  369: United States
  370: Panama
  371: Panama
  372: Panama
  375: Saint Vincent and the Grenadines
  376: Saint Vincent and the Grenadines
  377: Saint Vincent and the Grenadines
  378: British Virgin Islands
  379: United States Virgin Islands
  401: Afghanistan
  403: Saudi Arabia
  405: Bangladesh
  408: Bahrain
  410: Bhutan
  412: China
  413: China
  414: China
  416: Taiwan
  417: Sri Lanka
  419: India
  422: Iran
  423: Azerbaijan
  425: Iraq
  428: Israel
  431: Japan
  432: Japan
  434: Turkmenistan
  436: Kazakhstan
  437: Uzbekistan
  438: Jordan
  440: Korea
  441: Korea
  443: Palestine
  445: North Korea
  447: Kuwait
  450: Lebanon
  451: Kyrgyzstan
  453: Macao
  455: Maldives
  457: Mongolia
  459: Nepal
  461: Oman
  463: Pakistan
  466: Qatar
  468: Syria
  470: United Arab Emirates
  473: Yemen
  475: Yemen
  477: Hong Kong
  478: Bosnia and Herzegovina
  501: Adelie Land
