name: Update last vessels location

on:
  schedule:
    - cron: "15,30,55 * * * *"
  workflow_dispatch:

jobs:
  run-function:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run the function
      - name: Run GfsLastrunPipeline
        run: |
          python -c "from src.pipeline.data_pipeline import UpdateVesselsLocation; UpdateVesselsLocation()"
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}